/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.twosum;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void testOne() {
        int[] nums = {2, 7, 11, 15};
        int target = 9;
        int[] result = App.twoSum(nums, target);

        assertEquals(2, result.length);
        assertEquals(0, result[0]);
        assertEquals(1, result[1]);
    }

    @Test
    void testTwo() {
        int[] nums = {2, 1, 0, -1, -2};
        int target = 0;
        int[] result = App.twoSum(nums, target);

        assertEquals(2, result.length);
        assertEquals(1, result[0]);
        assertEquals(3, result[1]);
    }
}
