/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.palindromenumber;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void testOne() {
        int num = 121;
        boolean result = App.isPalindrome(num);

        assertEquals(true, result);
    }

    @Test
    void testTwo() {
        int num = -121;
        boolean result = App.isPalindrome(num);

        assertEquals(false, result);
    }
}
