/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.palindromenumber;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void exampleOne() {
        int input = 121;
        boolean result = Library.isPalindrome(input);

        assertEquals(true, result);
    }

    @Test
    void exampleTwo() {
        int input = -121;
        boolean result = Library.isPalindrome(input);

        assertEquals(false, result);
    }

    @Test
    void exampleThree() {
        int input = 10;
        boolean result = Library.isPalindrome(input);

        assertEquals(false, result);
    }
}
