/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.removeelement;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static int removeElement(int[] nums, int val) {
        int endIndex = 0;

        for (int i = 0; i < nums.length; ++i) {
            if (nums[i] != val) {
                nums[endIndex] = nums[i];
                endIndex += 1;
            }
        }

        return endIndex;
    }
}
