/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.coursescheduleii;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.text.MessageFormat;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

class LibraryTest {
    @Test
    void testExampleOne() throws Exception {
        int numCourses = 2;
        int[][] prereqs = {{1, 0}};
        List<Integer> result =
                toIntegerList(Library.findOrder(numCourses, prereqs));
        List<Integer> ans = List.of(0, 1);

        System.out.println(MessageFormat
                .format("Test One:\nExpected: {0}\nFound: {1}\n", ans, result));
        assertTrue(ans.equals(result));
    }

    @Test
    void testExampleTwo() throws Exception {
        int numCourses = 4;
        int[][] prereqs = {{1, 0}, {2, 0}, {3, 1}, {3, 2}};
        List<Integer> result =
                toIntegerList(Library.findOrder(numCourses, prereqs));
        List<List<Integer>> ans = Arrays.asList(Arrays.asList(0, 1, 2, 3),
                Arrays.asList(0, 2, 1, 3));

        System.out.println(MessageFormat
                .format("Test One:\nExpected: {0}\nFound: {1}\n", ans, result));

        assertTrue(ans.contains(result));
    }

    @Test
    void testExampleThree() throws Exception {
        int numCourses = 1;
        int[][] prereqs = {};
        List<Integer> result =
                toIntegerList(Library.findOrder(numCourses, prereqs));
        List<Integer> ans = List.of(0);

        System.out.println(MessageFormat
                .format("Test One:\nExpected: {0}\nFound: {1}\n", ans, result));
        assertTrue(ans.equals(result));
    }

    static List<Integer> toIntegerList(int[] arr) {
        return Arrays.stream(arr).boxed().collect(Collectors.toList());
    }
}
