/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.removeelement;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testOne() {
        int[] nums = {3, 2, 2, 3};
        int val = 3;
        int result = App.removeElement(nums, val);

        assertEquals(2, result);
    }

    @Test
    void testTwo() {
        int[] nums = {0, 1, 2, 2, 3, 0, 4, 2};
        int val = 2;
        int result = App.removeElement(nums, val);

        assertEquals(5, result);
    }

    @Test
    void testEmpty() {
        int[] nums = {};
        int val = 1;
        int result = App.removeElement(nums, val);

        assertEquals(0, result);
    }
}
