/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.longestcommonprefix;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void exampleOne() {
        String[] input = {"flower", "flow", "flight"};
        String result = Library.longestCommonPrefix(input);

        assertEquals("fl", result);
    }

    @Test
    void exampleTwo() {
        String[] input = {"dog", "racecar", "car"};
        String result = Library.longestCommonPrefix(input);

        assertEquals("", result);
    }

    @Test
    void singleString() {
        String[] input = {"a"};
        String result = Library.longestCommonPrefix(input);

        assertEquals("a", result);
    }
}
