/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.romantointeger;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    void exampleOne() {
        String input = "III";
        int result = Library.romanToInt(input);

        assertEquals(3, result);
    }

    @Test
    void exampleTwo() {
        String input = "IV";
        int result = Library.romanToInt(input);

        assertEquals(4, result);
    }

    @Test
    void exampleThree() {
        String input = "IX";
        int result = Library.romanToInt(input);

        assertEquals(9, result);
    }

    @Test
    void exampleFour() {
        String input = "LVIII";
        int result = Library.romanToInt(input);

        assertEquals(58, result);
    }

    @Test
    void exampleFive() {
        String input = "MCMXCIV";
        int result = Library.romanToInt(input);

        assertEquals(1994, result);
    }
}
