/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.removeduplicatesfromsortedarray;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static int removeDuplicates(int[] nums) {
        if (nums.length <= 1) {
            return nums.length;
        }

        int end = 1;
        int prev = nums[0];

        for (int i = 0; i < nums.length; ++i) {
            int cur = nums[i];
            if (cur != prev) {
                nums[end] = cur;
                end += 1;
            }
            prev = cur;
        }

        return end;
    }
}
