/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.singlenumber;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testOne() {
        int[] nums = {2, 2, 1};
        int result = App.singleNumber(nums);

        assertEquals(1, result);
    }

    @Test
    void testTwo() {
        int[] nums = {4, 1, 2, 1, 2};
        int result = App.singleNumber(nums);

        assertEquals(4, result);
    }
}
