/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.palindromelinkedlist;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void testOne() {
        Library.ListNode input = Library.makeList(new int[]{1, 2});
        boolean result = Library.isPalindrome(input);

        assertEquals(false, result);
    }

    @Test
    void testTwo() {
        Library.ListNode input = Library.makeList(new int[]{1, 2, 2, 1});
        boolean result = Library.isPalindrome(input);

        assertEquals(true, result);
    }

    @Test
    void testEmpty() {
        Library.ListNode input = Library.makeList(new int[]{});
        boolean result = Library.isPalindrome(input);

        assertEquals(true, result);
    }

    @Test
    void testNegative() {
        Library.ListNode input = Library.makeList(new int[]{-129, -129});
        {
            Library.ListNode node = input;
            while (node != null) {
                System.out.println(node.val);
                node = node.next;
            }
        }
        boolean result = Library.isPalindrome(input);

        assertEquals(true, result);
    }
}
