/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.containerwithmostwater;

public class Library {
    public static int maxArea(int[] height) {
        int max = 0;
        int left = 0;
        int right = height.length - 1;

        while (left < right) {
            max = Math.max(max, Math.min(height[left], height[right]) * (right - left));
            if (height[left] < height[right]) {
                left += 1;
            } else {
                right -= 1;
            }
        }

        return max;
    }
}
