/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennnedy.twosum;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;

class LibraryTest {
    @Test
    void exampleOne() {
        int[] input = {2, 7, 11, 15};
        int target = 9;
        int[] result = Library.twoSum(input, target);

        assertTrue(Arrays.equals(new int[]{0, 1}, result));
    }
}
