/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.lengthoflongestsubstring;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void testOne() {
        String s = "abcabcbb";
        int result = App.lengthOfLongestSubstring(s);

        assertEquals(3, result);
    }

    @Test
    void testTwo() {
        String s = "bbbb";
        int result = App.lengthOfLongestSubstring(s);

        assertEquals(1, result);
    }

    @Test
    void testThree() {
        String s = "pwwkew";
        int result = App.lengthOfLongestSubstring(s);

        assertEquals(3, result);
    }
}
