/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.singlenumber;

import java.util.Arrays;

public class App {
    public static int singleNumber(int[] nums) {
        return Arrays.stream(nums).reduce(0, (acc, num) -> acc ^ num);
    }
}
