/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.validparentheses;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    void exampleOne() {
        var input = "()";
        var result = Library.isValid(input);

        assertEquals(true, result);
    }

    @Test
    void exampleTwo() {
        var input = "()[]{}";
        var result = Library.isValid(input);

        assertEquals(true, result);
    }

    @Test
    void exampleThree() {
        var input = "(]";
        var result = Library.isValid(input);

        assertEquals(false, result);
    }

    @Test
    void exampleFour() {
        var input = "([)]";
        var result = Library.isValid(input);

        assertEquals(false, result);
    }

    @Test
    void exampleFive() {
        var input = "{[]}";
        var result = Library.isValid(input);

        assertEquals(true, result);
    }

    @Test
    void singleOpen() {
        var input = "(";
        var result = Library.isValid(input);

        assertEquals(false, result);
    }

    @Test
    void singleClosed() {
        var input = ")";
        var result = Library.isValid(input);

        assertEquals(false, result);
    }

}
