/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.removeduplicatesfromsortedarray;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testOne() {
        int[] nums = {1, 1, 2};
        int result = App.removeDuplicates(nums);

        assertEquals(2, result);
    }

    @Test
    void testTwo() {
        int[] nums = {0, 0, 1, 1, 1, 2, 2, 3, 3, 4};
        int result = App.removeDuplicates(nums);

        assertEquals(5, result);
    }

    @Test
    void testEmpty() {
        int[] nums = {};
        int result = App.removeDuplicates(nums);

        assertEquals(0, result);
    }

    @Test
    void testSingle() {
        int[] nums = {0};
        int result = App.removeDuplicates(nums);

        assertEquals(1, result);
    }
}
