/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mkennedy.removeduplicatesfromsortedarray;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void exampleOne() {
        int[] input = {1, 1, 2};
        int result = Library.removeDuplicates(input);

        assertEquals(2, result);
    }

    @Test
    void exampleTwo() {
        int[] input = {0, 0, 1, 1, 1, 2, 2, 3, 3, 4};
        int result = Library.removeDuplicates(input);

        assertEquals(5, result);
    }
}
